name: OTZ-Ads - Prebid.js 

on:
  push:
    branches: [ "pipeline-actions" ]

jobs:
  build:
    runs-on: ubuntu-latest
  
    steps:
    - name: Checkout repository    
      uses: actions/checkout@v3

    - name: Use Node.js 
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Cache npm dependencies
      uses: actions/cache@v3
      with: 
        path: ~/.npm
        key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-npm-

    - name: Cache gulp-cli
      uses: actions/cache@v3
      with:
        path: ~/.npm-global
        key: ${{ runner.os }}-gulp-cli
        restore-keys: |
          ${{ runner.os }}-gulp-cli

    - name: Install npm dependencies
      run: npm ci
      
    - name: Install gulp-cli
      run: npm install -g gulp-cli
      
    - name: Build project with Gulp
      run: |
        gulp build --modules=modules.json        
    
    - name: Upload to S3 Bucket
      run: |
        aws s3 sync build/dist s3://${{ secrets.S3_BUCKET }}/prebid/ --region ${{ secrets.S3_BUCKET_REGION }} --delete
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}       
