name: OTZ-Ads - Prebid.js 

on:
  push:
    branches: [ "pipeline-actions" ]

jobs:
  build:
    runs-on: ubuntu-latest  
    steps:
    - name: Checkout repository    
      uses: actions/checkout@v4

    - name: Cache npm dependencies
      uses: actions/setup-node@v3
      with: 
        node-version: 18
        cache: 'npm'

    - name: Install npm dependencies
      run: npm ci      
      
    - name: Build project with Gulp
      run: |
        gulp build --modules=modules.json        
  
    - name: Upload to S3 Bucket
      run: |
        aws s3 cp build/dist/prebid.js s3://${{ secrets.AWS_S3_BUCKET }} --region ${{ secrets.AWS_S3_REGION }}
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    - name: Invalidate Cloudflare Cache
      run: |
        curl -X POST "https://api.cloudflare.com/client/v4/zones/${{ secrets.CLOUDFLARE_ZONE_ID }}/purge_cache" \
        -H "Authorization: Bearer ${{ secrets.CLOUDFLARE_API_KEY }}" \
        -H "Content-Type: application/json" \
        --data '{
          "files": ["https://{{ secrets.DOMAIN_PATH }}/prebid.js"]
        }'
