name: OTZ-Ads - Prebid.js 

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository    
    - uses: actions/checkout@v3

    - name: Use Node.js 
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Cache npm dependencies
      uses: actions/cache@v3
      with: 
        path: ~/.npm
        key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-npm-

    - name: Install npm dependencies
      run: npm ci
      
    - name: Install gulp-cli
      run: npm install -g gulp-cli

    - name: Build project with Gulp
      run: |
        gulp build --modules=modules.json
