name: OTZ-Ads - Prebid.js 

on:
  push:
    branches: [ "feat/notification-slack" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest  
    env:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      
    steps:    
    - name: Slack Notification - Started
      uses: actions/slack@v1
      with: 
        status: starting
        channel: '#builds'
        message: Starting Build ${{ github.repository }}
      if: always()
        
    - name: Checkout repository    
      uses: actions/checkout@v4

    - name: Cache npm dependencies
      uses: actions/setup-node@v3
      with: 
        node-version: 18
        cache: 'npm'

    - name: Install npm dependencies
      run: npm ci      
      
    - name: Build project with Gulp
      run: |
        gulp build --modules=modules.json        
  
    - name: Upload to S3 Bucket
      run: |
        aws s3 cp build/dist/prebid.js s3://${{ secrets.AWS_S3_BUCKET }} --region ${{ secrets.AWS_S3_REGION }}
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    - name: Invalidate Cloudflare Cache
      run: |
        curl -s --connect-timeout 1 -X POST "https://api.cloudflare.com/client/v4/zones/${{ secrets.CLOUDFLARE_ZONE_ID }}/purge_cache" \
        -H "Authorization: Bearer ${{ secrets.CLOUDFLARE_API_KEY }}" \
        -H "Content-Type: application/json" \
        --data '{
          "files": ["https://tags.otzads.net/prebid/prebid.js"]
        }'
       
    - name: Slack Notification - Finished
      uses: actions/slack@v1
      with: 
        status: ${{ job.status }}
        channel: '#meetups'
        message: Deploy ${{ job.status }}
      if: always() 
